name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token vcp_2J40afC9jDsHnppycvVdEugPFKJdepV0nDZkezbKULuR0Zv5iT1BOx3s
        env:
          VERCEL_ORG_ID: team_DLLqFJ6w8hdn2OTIHeKaoKBq
          VERCEL_PROJECT_ID: prj_pDXubW3LsGy1zOaqHpsiyuBrP7ah
